TIMEOUT_MINUTES: int = 30

# Ответ на ключевые слова
KEYWORD_RESPONSES_ENABLE = True
TIMEOUT_RESPONSES_ENABLE = True
WHO_REQUEST_ENABLE = True
BOT_TAG_ENABLE = True
MASLINA_ENABLE = True
ERRORS_PARSE_ENABLE = True
HELP_EPA_MESSAGE_ENABLE = True

# Commands
ADD_CHAT_ENABLE = False
REMOVE_CHAT_ENABLE = False
ANNOUNCE_ENABLE = False
DOCS_ENABLE = True
HELP_ENABLE = True
SEARCH_ENABLE = True
BEST_QA_ENABLE = True
BEST_QA_STAT_ENABLE = True
GET_CHAT_LIST = False
GET_EPA_GUIDE_ENABLE = True
GET_EPA_CONTACTS_ENABLE = True
VTB_SUPPORT_ENABLE = True

# Dushnila scoring
DUSHNILA_ENABLE = True
DUSHNILA_WEEKLY_ENABLE = True
DUSHNILA_ME_ENABLE = True
DUSHNILA_WHY_ENABLE = True
DUSHNILA_RESET_WEEK_ENABLE = True

# Scheduler
GOOD_MORNING_ENABLE = True
GOOD_MORNING_HOUR: int = 9
GOOD_MORNING_MINUTE: int = 0
DUSHNILA_DIGEST_HOUR: int = 18
DUSHNILA_DIGEST_MINUTE: int = 0

# Timings
SEARCH_TIMEOUT_SECONDS: int = 120
SEARCH_MAX_QUERY_LEN: int = 2000
WHO_REQUEST_COOLDOWN_SECONDS: int = 180 * 60
REACTION_TTL_SECONDS: int = 24 * 60 * 60
